# Generated by Django 4.2.7 on 2024-12-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='in_progress',
            new_name='progress',
        ),
    ]
